networks:
  wordpress:
    driver: bridge

services:
  db:
    image: mysql:5.7
    ports:
      - 9903:3306
    environment:
      MYSQL_DATABASE: db_example
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress

  php:
    build: ./php
    ports:
      - 9000:9000
    volumes:
      - ./wordpress:/var/www/html
      - ./plugin-dev:/var/www/html/web/app/plugins/wp-net-gross-calculator
      - ./plugin-dev/debug.log:/var/www/html/web/app/debug.log
    networks:
      - wordpress

  nginx:
    build: ./server
    volumes:
      - ./wordpress:/var/www/html
      - ./plugin-dev:/var/www/html/web/app/plugins/wp-net-gross-calculator
      - ./plugin-dev/debug.log:/var/www/html/web/app/debug.log
    ports:
      - "8000:80"
    depends_on:
      - php
      - db
    networks:
      - wordpress

volumes:
  db-data:
